name: Build LDC & LDC D unittests & defaultlib unittest runners
inputs:
  cmake_flags:
    required: false
    default: ''
  arch:
    required: false # Windows only
  with_pgo:
    required: false
    default: false
runs:
  using: composite
  steps:

    - name: 'Linux & Windows x86_64: Build symgc'
      if: (runner.os == 'Linux' && inputs.arch == 'x86_64') || (runner.os == 'Windows' && inputs.arch == 'x64')
      shell: bash
      run: |
        set -eux
        cd runtime/symgc
        # FIXME: hitting LLVM assertion with -g
        DFLAGS="-O -g -singleobj -linkonce-templates" dub build -v --compiler=$PWD/../../../bootstrap-ldc/bin/ldc2
        # extract single object file as symgc.o[bj]
        if [[ '${{ runner.os }}' == Linux ]]; then
          ls -l libsymgc.a
          ar x libsymgc.a
          mv *.o symgc.o
          ls -l symgc.o
        else
          ls -l symgc.lib
          #obj=$(lib.exe /nologo /list symgc.lib)
          #lib.exe /nologo symgc.lib /extract:"$obj" /out:symgc.obj
          llvm-ar x symgc.lib
          mv *.obj symgc.obj
          ls -l symgc.obj
        fi

    - name: 'Posix: Build mimalloc'
      if: runner.os != 'Windows'
      uses: ./.github/actions/helper-mimalloc

    - name: Build LDC & LDC D unittests & defaultlib unittest runners
      uses: ./.github/actions/helper-build-ldc
      with:
        build_dir: build
        host_dc: ../bootstrap-ldc/bin/ldmd2
        specify_install_dir: true
        cmake_flags: >-
          ${{ runner.os != 'Windows' && '-DALTERNATIVE_MALLOC_O="$PWD/../build-mimalloc/CMakeFiles/mimalloc-obj.dir/src/static.c.o"' || '' }}
          ${{ inputs.cmake_flags }}
          ${{ inputs.with_pgo == 'true' && '-DDFLAGS_LDC=-fprofile-use=../pgo-ldc/merged.profdata' || '' }}
        build_targets: all ldc2-unittest all-test-runners
        arch: ${{ inputs.arch }}

    - run: ../build/bin/ldc2 --version
      shell: bash
